name: Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install package.json
    - name: Run ESLint
      run: node node_modules/eslint/bin/eslint.js . --ext .js,.jsx,.ts,.tsx